apiVersion: ai.sap.com/v1alpha1
kind: ServingTemplate
metadata:
  name: deepseek-r1-7b-stable
  annotations:
    scenarios.ai.sap.com/description: "DeepSeek-R1 7B - V0 engine (stable)"
    scenarios.ai.sap.com/name: "deepseek-r1-7b-stable"
    executables.ai.sap.com/description: "7B model with V0 engine"
    executables.ai.sap.com/name: "deepseek-r1-7b-stable"
  labels:
    scenarios.ai.sap.com/id: "deepseek-r1-7b-stable"
    ai.sap.com/version: "1.0.0"
spec:
  inputs:
    parameters:
      - name: modelName
        default: "deepseek-ai/DeepSeek-R1-Distill-Qwen-7B"
        type: string
      
      - name: dataType
        default: "float16"
        type: string
      
      - name: gpuMemoryUtilization
        default: "0.80"
        type: string
      
      - name: maxModelLen
        default: "8192"
        type: string
      
      - name: maxNumBatchedTokens
        default: "8192"
        type: string
      
      - name: maxNumSeqs
        default: "64"
        type: string
      
      - name: tensorParallelSize
        default: "1"
        type: string
      
      - name: resourcePlan
        type: string
        default: "infer.l"
        
  template:
    apiVersion: "serving.kserve.io/v1beta1"
    metadata:
      annotations: |
        autoscaling.knative.dev/metric: concurrency
        autoscaling.knative.dev/target: 1
        autoscaling.knative.dev/targetBurstCapacity: 0
      labels: |
        ai.sap.com/resourcePlan: "{{inputs.parameters.resourcePlan}}"
    spec: |
      predictor:
        imagePullSecrets:
        - name: olamagit
        minReplicas: 1
        maxReplicas: 1
        containers:
        - name: kserve-container
          image: docker.io/jeyasinghsamuelponnusamydur043/vllm:ai-core-vllm
          ports:
            - containerPort: 8000
              protocol: TCP
          command: ["/bin/sh", "-c"]
          args:
            - >
              set -e && echo "Starting DeepSeek-R1 7B with V0 engine" 
              && python3 -m vllm.entrypoints.openai.api_server 
              --model {{inputs.parameters.modelName}}
              --dtype {{inputs.parameters.dataType}}
              --gpu-memory-utilization {{inputs.parameters.gpuMemoryUtilization}}
              --max-model-len {{inputs.parameters.maxModelLen}}
              --max-num-batched-tokens {{inputs.parameters.maxNumBatchedTokens}}
              --max-num-seqs {{inputs.parameters.maxNumSeqs}}
              --tensor-parallel-size {{inputs.parameters.tensorParallelSize}}
              --trust-remote-code
              --disable-log-requests
              --host 0.0.0.0
              --port 8000
          env:
            - name: MODEL
              value: "{{inputs.parameters.modelName}}"
            - name: VLLM_USE_V1
              value: "0"
            - name: VLLM_WORKER_MULTIPROC_METHOD
              value: "spawn"
            - name: HF_HOME
              value: "/tmp/huggingface"
