apiVersion: ai.sap.com/v1alpha1
kind: ServingTemplate
metadata:
  name: deepseek-r1-vllm
  annotations:
    scenarios.ai.sap.com/description: "Run DeepSeek-R1 reasoning model on SAP AI Core with vLLM"
    scenarios.ai.sap.com/name: "deepseek-r1-vllm"
    executables.ai.sap.com/description: "Deploy DeepSeek-R1 (671B or distilled models) with vLLM inference server"
    executables.ai.sap.com/name: "deepseek-r1-vllm"
  labels:
    scenarios.ai.sap.com/id: "deepseek-r1-vllm"
    ai.sap.com/version: "1.0.0"
spec:
  inputs:
    parameters:
      - name: modelName
        default: "deepseek-ai/DeepSeek-R1-Distill-Qwen-14B"
        type: string
        description: "DeepSeek-R1 model variant"
      
      - name: dataType
        default: "auto"
        type: string
        description: "Data type for model weights (auto, bfloat16, float16)"
      
      - name: gpuMemoryUtilization
        default: "0.90"
        type: string
        description: "GPU memory utilization (0.8-0.95 recommended)"
      
      - name: maxModelLen
        default: "32768"
        type: string
        description: "Maximum context length (32K default, supports up to 128K)"
      
      - name: maxNumBatchedTokens
        default: "32768"
        type: string
        description: "Maximum batched tokens per iteration"
      
      - name: maxNumSeqs
        default: "256"
        type: string
        description: "Maximum sequences per iteration"
      
      - name: tensorParallelSize
        default: "1"
        type: string
        description: "Number of GPUs for tensor parallelism"
      
      - name: quantization
        default: "None"
        type: string
        description: "Quantization method: None, awq, gptq, fp8"
      
      - name: additionalArgs
        default: "--enable-expert-parallel --trust-remote-code"
        type: string
        description: "Additional vLLM arguments. Default enables expert parallelism and trust remote code"
      
      - name: resourcePlan
        type: string
        default: "train.l"
        description: "Resource Plan: infer.l (1 GPU), train.l (4 GPUs), train.xl (8 GPUs)"

  template:
    apiVersion: "serving.kserve.io/v1beta1"
    metadata:
      annotations: |
        autoscaling.knative.dev/metric: concurrency
        autoscaling.knative.dev/target: 1
        autoscaling.knative.dev/targetBurstCapacity: 0
      labels: |
        ai.sap.com/resourcePlan: "{{inputs.parameters.resourcePlan}}"
    spec: |
      predictor:
        imagePullSecrets:
        - name: olamagit
        minReplicas: 1
        maxReplicas: 1
        containers:
        - name: kserve-container
          image: docker.io/jeyasinghsamuelponnusamydur043/vllm:ai-core-vllm
          ports:
            - containerPort: 8000
              protocol: TCP
          command: ["/bin/sh", "-c"]
          args:
            - >
              set -e && echo "-------------Starting DeepSeek-R1 with vLLM OpenAI API Server--------------" 
              && python3 -m vllm.entrypoints.openai.api_server 
              --model {{inputs.parameters.modelName}}
              --dtype {{inputs.parameters.dataType}}
              --gpu-memory-utilization {{inputs.parameters.gpuMemoryUtilization}}
              --max-model-len {{inputs.parameters.maxModelLen}}
              --max-num-batched-tokens {{inputs.parameters.maxNumBatchedTokens}}
              --max-num-seqs {{inputs.parameters.maxNumSeqs}}
              --tensor-parallel-size {{inputs.parameters.tensorParallelSize}}
              --host 0.0.0.0
              --port 8000
              {{inputs.parameters.additionalArgs}}
          env:
            - name: MODEL
              value: "{{inputs.parameters.modelName}}"
            - name: VLLM_USE_V1
              value: "1"
            - name: HF_HOME
              value: "/tmp/huggingface"
          resources:
            limits:
              nvidia.com/gpu: {{inputs.parameters.tensorParallelSize}}
