apiVersion: ai.sap.com/v1alpha1
kind: ServingTemplate
metadata:
  name: vllm
  annotations:
    scenarios.ai.sap.com/description: "Run a vllm server on SAP AI Core"
    scenarios.ai.sap.com/name: "vllm"
    executables.ai.sap.com/description: "ollama service"
    executables.ai.sap.com/name: "vllm"
  labels:
    scenarios.ai.sap.com/id: "vllm"
    ai.sap.com/version: "0.0.1"
spec:
  template:
    apiVersion: "serving.kserve.io/v1beta1"
    metadata:
      annotations: |
        autoscaling.knative.dev/metric: concurrency
        autoscaling.knative.dev/target: 1
        autoscaling.knative.dev/targetBurstCapacity: 0
      labels: |
        ai.sap.com/resourcePlan: infer.l
    spec: |
      predictor:
        imagePullSecrets:
        - name: olamagit
        minReplicas: 1
        maxReplicas: 1
        containers:
        - name: kserve-container
          image: docker.io/jeyasinghsamuelponnusamydur043/vllm:ai-core-vllm
          ports:
            - containerPort: 8080
              protocol: TCP
